# Professional Mission Report Generator
import json

class ReportBuilder:
    def __init__(self, metadata=None):
        self.meta = metadata or {"author": "E.D.I.T.H Titan", "version": "2.5"}

    def generate_markdown(self, mission_name, findings):
        report = f"# Mission SUCCESS: {mission_name}\n"
        report += f"**Strategist**: {self.meta['author']} // **Kernel**: {self.meta['version']}\n\n"
        report += "## Operational Findings\n"
        for key, val in findings.items():
            report += f"- **{key}**: {val}\n"
        report += "\n--- \n*Generated by MANS/ATT Protocol*"
        return report

    def save_to_file(self, content, filename="mission_report.md"):
        with open(filename, 'w') as f:
            f.write(content)
        return filename
